server:
  port: 8000
 
eureka:  client:    register-with-eureka: true 
  
spring:  datasource:    url: jdbc:mysql://localhost:3306/sprint_security
    username: root
    password: manu2462
    
    
#  jpa:#    hibernate:#      ddl-auto: update