server:
  port: 8090
  
  
spring:
  application:
    name: Client-service
    
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#      path: /console

  data:
    mongodb:
      host: localhost
      port: 27017
      database: user
      
  main:
    allow-bean-definition-overriding: true
      
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
      
      